[package]
name = "disk-image-inspector"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codepage-437 = "^0.1"
chrono = "^0.4"
env_logger = "^0.9"
getopts = "^0.2"
hex = "^0.4"
log = "^0.4"
phf = { version = "^0.10", features = ["macros"]}
uuid = "^0.8"